apiVersion: v1
kind: Secret
metadata:
  name: backend-qts-secret # Required. Name your secret.
  namespace: trident
type: Opaque
stringData:
  username: user # Required. Your NAS username.
  password: 0000 # Required. Your NAS password.
  chapInitiatorUsername: <initiator_username> # Optional. Username used by the initiator to authenticate to the target.
  chapInitiatorPassword: <initiator_password> # Optional. Password for the initiator’s CHAP authentication. 
  chapTargetUsername: <target_username> # Optional. Username used by the target to authenticate back to the initiator (for mutual CHAP).
  chapTargetPassword: <target_password> # Optional. Password for the target’s CHAP authentication (for mutual CHAP). 
  storageAddress: 0.0.0.0 # Required. Your NAS IP address.
  https: false # Optional. Whether to enable a secure connection. Default: False.
  port: 8080 # Optional. Specify the port. Default: 8080.
  trustedCACertificate: <Base64-encoded-trusted-ca-certificate-for-backend> # Optional. Base64-encoded value of trusted CA certificate. Used for certificate-based authentication. 
---
apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-qts # Required. Name your backend in Kubernetes.
  namespace: trident
spec:
  version: 1
  storageDriverName: qnap-nas #Required. Support 'qnap-nas'(latest) or 'qnap-iscsi'
  backendName: qts # Required. Name your backend in QNAP CSI.
  networkInterfaces: ["Adapter1"] # Optional. Your adapter name or leave it empty.
  userCHAP: true # Optional. Enables CHAP authentication for iSCSI connections. 
  credentials:
    name: backend-qts-secret # Required. Enter the secret name set in metadata.name.
  debugTraceFlags:
    method: true
  storage: # Required. Define one or more virtual pools.
    - serviceLevel: pool1 # Required. Name your virtual pool.
      labels: # Required. Define custom labels for your virtual pool.
        performance: performance1
      features: # Optional. Define features for your virtual pool.
        tiering: Enable
    - serviceLevel: pool2
      labels:
        performance: performance2
      features:
        tiering: Enable
        ssdCache: "true"
        raidLevel: "1"